# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOMEI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOMEI
  pod 'Cosmos', '~> 22.1'
  pod 'CPF-CNPJ-Validator'
  pod 'ALCameraViewController'
  pod 'Firebase/Storage'
  pod 'YYCalendar'

end
